'use strict';
(() => {
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
const W=320,H=240,FLOOR=207,HOOP={x:274,y:105},C={ink:'#19162f',night:'#242342',purple:'#503b69',pink:'#ee5e72',gold:'#ffd166',orange:'#f69648',wood:'#b96e45',wood2:'#cc8051',line:'#fce5b0',blue:'#55c5cc',white:'#fff4d6'};
const keys={left:false,right:false,jump:false,shoot:false};let state='title',time=60,score=[0,0],streak=0,shake=0,flash=0,banner='',bannerTime=0,particles=[],trail=[],crowd=[],ball,player,enemy,frame=0,last=0,acc=0,muted=false,audio=null,owner='player',aiShotAt=0;
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
function text(t,x,y,size=9,color=C.white){ctx.font=`900 ${size}px monospace`;ctx.textAlign='center';ctx.textBaseline='top';ctx.fillStyle=C.ink;ctx.fillText(t,Math.round(x)+1,Math.round(y)+2);ctx.fillStyle=color;ctx.fillText(t,Math.round(x),Math.round(y))}
function reset(){time=60;score=[0,0];streak=0;shake=flash=0;banner='';bannerTime=0;particles=[];trail=[];frame=0;player={x:74,y:FLOOR,vx:0,vy:0,face:1,charge:0,cool:0,pose:'idle'};enemy={x:224,y:FLOOR,vx:0,vy:0,face:-1,charge:0,cool:0,pose:'idle'};ball={x:82,y:190,vx:0,vy:0,spin:0,scored:false,last:'player',value:2,dunk:false};owner='player';aiShotAt=0;state='play';sound('start')}
for(let i=0;i<65;i++)crowd.push({x:i*5+rand(-2,2),y:40+Math.floor(i%3)*9,c:i%5===0?C.gold:i%3===0?C.pink:C.blue,phase:rand(0,6)});
function beep(freq,duration=.1,type='square',vol=.04,slide=0){if(muted)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const osc=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;osc.type=type;osc.frequency.setValueAtTime(freq,now);if(slide)osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),now+duration);gain.gain.setValueAtTime(vol,now);gain.gain.exponentialRampToValueAtTime(.001,now+duration);osc.connect(gain).connect(audio.destination);osc.start(now);osc.stop(now+duration)}catch(e){/* Audio is optional. */}}
function sound(s){if(s==='bounce')beep(115,.07,'triangle',.035,-60);if(s==='throw')beep(330,.12,'square',.025,140);if(s==='score'){beep(523,.23,'square',.035,260);setTimeout(()=>beep(785,.27,'square',.035),115)}if(s==='dunk'){beep(85,.3,'sawtooth',.065,-40);setTimeout(()=>beep(590,.2,'square',.035),110)}if(s==='crowd'){for(let i=0;i<5;i++)setTimeout(()=>beep(rand(100,260),.07,'sawtooth',.007),i*42)}if(s==='start')beep(392,.18,'square',.035);if(s==='jump')beep(205,.1,'triangle',.025,100)}
function moveChar(a,dir,speed){a.vx+=(dir*speed-a.vx)*.24;a.x=clamp(a.x+a.vx,11,307);if(Math.abs(a.vx)>.3)a.face=Math.sign(a.vx);a.y+=a.vy;a.vy+=.24;if(a.hang>0){a.hang--;a.y=HOOP.y+28;a.x=HOOP.x-9;a.vx=0;a.vy=0;if(a.hang===0)a.vy=.8}if(a.y>=FLOOR){a.y=FLOOR;a.vy=0}if(a.cool>0)a.cool--;a.pose=a.y<FLOOR?'jump':Math.abs(a.vx)>.55?'run':'idle'}
function jump(a){if(a.y>=FLOOR){a.vy=-4.55;sound('jump')}}
function release(who){const a=who==='player'?player:enemy;if(owner!==who||a.cool>0)return;const charge=clamp(a.charge,0,1),near=Math.abs(a.x-HOOP.x)<35&&a.y<FLOOR-12&&who==='player';a.charge=0;a.cool=28;owner=null;ball.x=a.x+8;ball.y=a.y-18;ball.scored=false;ball.last=who;ball.value=who==='player'&&a.x<128?3:2;ball.dunk=near;if(near)a.hang=22;const dx=HOOP.x-ball.x,dy=HOOP.y-ball.y;
if(near){ball.x=HOOP.x-2;ball.y=HOOP.y-9;ball.vx=.35;ball.vy=1;banner='¡DUNK!';bannerTime=.55;sound('dunk')}
else{const flight=clamp(Math.abs(dx)/(2+charge*1.3),50,76),error=who==='player'?((1-charge)*rand(-24,24)+rand(-6,6)):rand(-24,24);ball.vx=dx/flight;ball.vy=(dy+error-.0525*flight*flight)/flight;sound('throw')}}
function burst(x,y,n=32){for(let i=0;i<n;i++)particles.push({x,y,vx:rand(-2.5,2.5),vy:rand(-3.7,.1),life:rand(28,65),c:[C.gold,C.pink,C.blue,C.white,C.orange][i%5]})}
function scoreBall(){const side=ball.last==='player'?0:1;score[side]+=ball.value;ball.scored=true;owner=null;shake=side===0?8:4;flash=.65;burst(HOOP.x,HOOP.y,46);if(side===0){streak++;banner=ball.dunk?'¡DUNK!':ball.value===3?'¡3 POINTS!':'¡SWISH!';if(streak>=3)banner='¡HOT STREAK!'}else{streak=0;banner='RIVAL +2'}bannerTime=1.3;sound(ball.dunk?'dunk':'score');sound('crowd');ball.vx*=.35;ball.vy=1.5}
function updateBall(){if(owner){const a=owner==='player'?player:enemy;ball.x=a.x+a.face*8;ball.y=a.y-15+(a.pose==='idle'?Math.abs(Math.sin(frame*.13))*6:Math.abs(Math.sin(frame*.3))*3);ball.spin+=.1;return}
const oldY=ball.y;trail.push({x:ball.x,y:ball.y,life:13});if(trail.length>14)trail.shift();ball.x+=ball.vx;ball.y+=ball.vy;ball.vy+=.105;ball.vx*=.9998;ball.spin+=ball.vx*.15;
if(!ball.scored&&ball.vy>0&&oldY<=HOOP.y-2&&ball.y>=HOOP.y-2&&Math.abs(ball.x-HOOP.x)<8)scoreBall();
if(ball.x<5||ball.x>315){ball.x=clamp(ball.x,5,315);ball.vx*=-.68;sound('bounce')}
if(ball.y>FLOOR-4){ball.y=FLOOR-4;ball.vy=Math.abs(ball.vy)>.75?-Math.abs(ball.vy)*.55:0;ball.vx*=.85;if(Math.abs(ball.vy)>.7)sound('bounce')}
if(ball.y<98&&ball.y>85&&ball.x>283&&ball.x<290&&ball.vx>0){ball.x=283;ball.vx*=-.75;sound('bounce')}
if(!ball.scored&&ball.vy>0&&ball.y>HOOP.y-5&&ball.y<HOOP.y+3&&Math.abs(ball.x-HOOP.x)>8&&Math.abs(ball.x-HOOP.x)<13){ball.vy=-Math.abs(ball.vy)*.65;ball.vx+=(ball.x<HOOP.x?-1:1)*.6;sound('bounce')}
if(ball.y>FLOOR-24&&Math.abs(ball.vx)<2){for(const [name,a] of [['player',player],['enemy',enemy]]){if(Math.abs(a.x-ball.x)<12&&a.cool<16){owner=name;ball.last=name;ball.scored=false;trail=[];break}}}}
function tick(dt){frame++;if(state!=='play')return;time=Math.max(0,time-dt);if(time===0){state='result';owner=null;sound('start');return}
const dir=Number(keys.right)-Number(keys.left);moveChar(player,dir,1.85);if(keys.jump){jump(player);keys.jump=false}if(keys.shoot&&owner==='player')player.charge=Math.min(1,player.charge+.018);
let aiDir=0;if(owner==='enemy'){aiDir=enemy.x>190?-1:enemy.x<155?1:0;enemy.charge=Math.min(1,enemy.charge+.008);aiShotAt++;if(aiShotAt>95&&enemy.cool===0){release('enemy');aiShotAt=0}}else{aiShotAt=0;const target=owner==='player'?player.x-11:ball.x;aiDir=Math.abs(target-enemy.x)>8?Math.sign(target-enemy.x):0;if(owner==='player'&&Math.abs(enemy.x-player.x)<25&&Math.random()<.013)jump(enemy)}moveChar(enemy,aiDir,1.25);
if(owner==='player'&&Math.abs(enemy.x-player.x)<11&&player.y>=FLOOR&&Math.random()<.007){owner=null;ball.vx=rand(-2,2);ball.vy=-1.7;streak=0;sound('bounce')}
updateBall();for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.065;p.life--}particles=particles.filter(p=>p.life>0);trail=trail.filter(p=>--p.life>0);shake=Math.max(0,shake-.35);flash=Math.max(0,flash-.035);bannerTime=Math.max(0,bannerTime-dt);
if(!muted&&frame%23===0){const melody=[196,247,294,247,220,262,330,262];beep(melody[Math.floor(frame/23)%8],.08,'square',.008)}}
function court(){rect(0,0,W,H,C.night);for(let y=34;y<84;y+=8){rect(0,y,W,1,C.purple);rect(0,y+3,W,2,'#34314e')}crowd.forEach(c=>{const j=state==='play'&&bannerTime>0?Math.floor(Math.sin(frame*.3+c.phase)*3):Math.floor(Math.sin(frame*.035+c.phase));rect(c.x,c.y+j,3,3,c.c);rect(c.x-1,c.y+3+j,5,5,C.ink);rect(c.x,c.y+3+j,3,3,c.c)});rect(0,78,W,5,C.purple);rect(0,84,W,4,C.ink);rect(0,89,W,119,C.wood);for(let y=90;y<208;y+=13){rect(0,y,W,1,C.wood2);for(let x=(Math.floor(y/13)%2)*28;x<W;x+=56)rect(x,y+1,1,12,'#a95f3c')}
rect(0,205,W,3,C.line);rect(125,167,2,40,C.line);rect(238,166,2,40,C.line);rect(238,166,68,2,C.line);rect(305,166,2,41,C.line);ctx.strokeStyle=C.line;ctx.lineWidth=2;ctx.beginPath();ctx.arc(125,205,49,Math.PI,Math.PI*2);ctx.stroke();rect(287,88,4,40,C.white);rect(287,88,13,3,C.pink);rect(264,102,22,3,C.orange);rect(266,105,19,2,C.white);for(let i=0;i<5;i++)rect(268+i*3,108,1,7+(i%2)*2,C.white);rect(269,116,13,1,C.white);rect(3,79,2,126,C.purple);rect(0,204,W,4,C.ink)}
function avatar(a,blue){const x=Math.round(a.x),y=Math.round(a.y),leg=a.pose==='run'?Math.round(Math.sin(frame*.38)*3):0,j=a.pose==='jump',celebrate=bannerTime>0&&a===player&&ball.scored;rect(x-5,y-2,4,3,C.ink);rect(x+2,y-2,4,3,C.ink);rect(x-4+leg,y-8,3,7,blue?C.blue:C.pink);rect(x+2-leg,y-8,3,7,blue?C.blue:C.pink);rect(x-6,y-21,12,13,blue?C.blue:C.pink);rect(x-4,y-20,8,5,blue?'#34959f':'#bc3d64');rect(x-4,y-28,9,8,'#d9946e');rect(x-5,y-28,10,3,blue?'#433348':'#572e3e');rect(x+a.face*2,y-24,1,1,C.ink);rect(x-8,y+(j||celebrate?-25:-12),3,8,'#d9946e');rect(x+6,y+(j||celebrate?-25:-17),3,8,'#d9946e');if(a.charge>0){rect(x-11,y-37,22,4,C.ink);rect(x-10,y-36,Math.round(20*a.charge),2,a.charge>.78?C.gold:C.blue)}}
function ballDraw(x,y,spin=0){rect(x-4,FLOOR,9,2,'#583b3d');x=Math.round(x);y=Math.round(y);rect(x-3,y-3,7,7,C.ink);rect(x-2,y-3,5,7,C.orange);rect(x-3,y-1,7,2,C.orange);rect(x-3,y,7,1,C.ink);rect(x+Math.round(Math.sin(spin)*2),y-3,1,7,C.ink);rect(x-2,y-2,1,1,C.gold)}
function hud(){rect(0,0,W,36,C.ink);rect(2,2,316,31,C.purple);rect(5,5,94,25,C.night);rect(111,5,98,25,C.night);rect(221,5,94,25,C.night);text('TÚ',51,7,7,C.blue);text(String(score[0]).padStart(2,'0'),51,15,13,C.white);text('TIEMPO',160,7,7,C.gold);text(String(Math.ceil(time)).padStart(2,'0')+':00',160,15,12,time<=10?C.pink:C.white);text('RIVAL',269,7,7,C.pink);text(String(score[1]).padStart(2,'0'),269,15,13,C.white);if(streak>=2)text('RACHA x'+streak,160,38,7,C.gold)}
function overlay(){rect(14,47,292,151,C.ink);rect(17,50,286,145,C.purple);rect(21,54,278,137,C.night);if(state==='title'){text('HOOP FURY',160,68,24,C.gold);text("'88",160,97,23,C.pink);text('60 SEGUNDOS. UNA CANCHA.',160,134,9,C.white);text('TÚ CONTRA LA MÁQUINA',160,149,9,C.blue);text('ENTER O TOCA PARA JUGAR',160,174,9,frame%45<34?C.gold:C.white)}else{const result=score[0]>score[1]?'¡VICTORIA!':score[0]<score[1]?'DERROTA':'¡EMPATE!';text(result,160,68,21,score[0]>=score[1]?C.gold:C.pink);text(`${score[0]} - ${score[1]}`,160,108,28,C.white);text('FIN DEL PARTIDO',160,148,10,C.blue);rect(78,168,164,20,C.pink);rect(81,170,158,16,C.ink);text('▶ REINICIAR',160,173,10,frame%45<34?C.gold:C.white)}}
function render(){ctx.save();ctx.translate(shake?Math.round(rand(-shake,shake)):0,shake?Math.round(rand(-shake/2,shake/2)):0);court();for(const p of trail)rect(p.x-2,p.y-2,4,4,p.life>7?C.gold:C.orange);avatar(enemy,false);avatar(player,true);ballDraw(ball.x,ball.y,ball.spin);for(const p of particles)rect(p.x,p.y,Math.max(1,Math.ceil(p.life/25)),3,p.c);hud();if(state==='play'&&bannerTime>0)text(banner,160,53+Math.sin(frame*.17)*3,banner==='¡HOT STREAK!'?16:21,C.gold);if(state!=='play')overlay();if(flash>0){ctx.globalAlpha=Math.min(.55,flash*.48);rect(0,0,W,H,C.white);ctx.globalAlpha=1}ctx.restore()}
function loop(t){const elapsed=Math.min(.1,(t-last)/1000||0);last=t;acc+=elapsed;while(acc>=1/60){tick(1/60);acc-=1/60}if(state!=='play')frame++;render();requestAnimationFrame(loop)}
function startOrReset(){if(state!=='play')reset()}
const mapping={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'jump',KeyW:'jump',Space:'shoot'};
window.addEventListener('keydown',e=>{if(mapping[e.code]){e.preventDefault();if(state!=='play'){startOrReset();return}if(mapping[e.code]==='shoot'&&!keys.shoot)player.charge=0;keys[mapping[e.code]]=true}else if(e.code==='Enter'){e.preventDefault();startOrReset()}});
window.addEventListener('keyup',e=>{if(mapping[e.code]){e.preventDefault();if(mapping[e.code]==='shoot'&&keys.shoot&&state==='play')release('player');keys[mapping[e.code]]=false}});
window.addEventListener('blur',()=>{if(keys.shoot&&state==='play')release('player');Object.keys(keys).forEach(k=>keys[k]=false)});
canvas.addEventListener('pointerdown',()=>startOrReset());
for(const b of document.querySelectorAll('[data-key]')){const key=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);startOrReset();if(key==='shoot'&&!keys.shoot)player.charge=0;keys[key]=true;b.classList.add('pressed')});const up=e=>{e.preventDefault();if(key==='shoot'&&keys.shoot&&state==='play')release('player');keys[key]=false;b.classList.remove('pressed')};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up)}
document.getElementById('sound').addEventListener('click',e=>{muted=!muted;e.currentTarget.textContent=`♫ SONIDO: ${muted?'NO':'SÍ'}`;if(!muted)beep(440)});
player={x:74,y:FLOOR,vx:0,vy:0,face:1,charge:0,cool:0,pose:'idle'};enemy={x:224,y:FLOOR,vx:0,vy:0,face:-1,charge:0,cool:0,pose:'idle'};ball={x:82,y:190,vx:0,vy:0,spin:0,scored:false};requestAnimationFrame(loop);
})();
